# -*- coding: utf-8 -*-
"""ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OJHI6o7hrfZlu4Js1-0oxp1_NVd4lpSL

![ANN](https://pbs.twimg.com/media/FN7ckZCX0AMpddJ?format=jpg&name=large)

Artificial neural networks are one of the main tools used in machine learning. As the “neural” part of their name suggests, they are brain-inspired systems that are intended to replicate the way that we humans learn. Neural networks consist of input and output layers, as well as (in most cases) a hidden layer consisting of units that transform the input into something that the output layer can use. They are excellent tools for finding patterns that are far too complex or numerous for a human programmer to extract and teach the machine to recognize.

[Click to See my Article on ANN](https://medium.com/machine-learning-researcher/artificial-neural-network-ann-4481fa33d85a)

![Machine Learning Project](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <font color = #950CDF> Part 1: </font> <font color = #4854E8> Information of Dataset </font>
<b>Titanic Data Set:</b> The sinking of the Titanic is one of the most infamous shipwrecks in history. On April 15, 1912, during her maiden voyage, the widely considered “unsinkable” RMS Titanic sank after colliding with an iceberg. Unfortunately, there weren’t enough lifeboats for everyone onboard, resulting in the death of 1502 out of 2224 passengers and crew. While there was some element of luck involved in surviving, it seems some groups of people were more likely to survive than others.

In this challenge, we build a ANN model that answers the question: “what sorts of people were more likely to survive?” using passenger data (ie name, age, gender, socio-economic class, etc).

https://www.kaggle.com/c/titanic/data

![ML](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### <font color = #27C3E5> 1.1: </font> <font color = #41EA46> Import Libraries and Dataset </font>

#### <font color = blue>Import the Libraries
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, mean_absolute_error, roc_auc_score

"""#### <font color = blue>Import the Dataset"""

df = pd.read_csv('/content/titanic.csv')
df.head()

"""### <font color = #27C3E5> 1.2: </font> <font color = #41EA46> Data Information and Visualization </font>

#### <font color = blue> View all Rows and Cols
"""

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

"""#### <font color = blue> Data Information"""

df.info()

"""#### <font color = blue> Visualize the Data Distributiuon"""

plt.style.use('fivethirtyeight')
sns.pairplot(df, hue = 'Survived')

"""#### <font color = blue> Visualize Target Class Label Distributiuon"""

Survival = df[df['Survived'] == 1].shape[0]
Notsurvival = df[df['Survived'] == 1].shape[0]

class_ = [Survival, Notsurvival]
label = ['Survival', 'Notsurvival']

plt.pie(class_, labels = label, shadow = True, wedgeprops = {'edgecolor': 'black'},
        autopct = '%1.1f%%', startangle= 90, colors=['red', 'green'])

plt.tight_layout()
plt.show()

"""![Machine Learning Project](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <font color = #950CDF> Part 2: </font> <font color = #4854E8> Data Preprocessing </font>

![ML](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### <font color = #27C3E5> 2.1: </font> <font color = #41EA46> Drop Unnecessary Cols </font>
"""

df = df.drop(["PassengerId", "Name", "Ticket", "Cabin"], axis = 1)
df.head(3)

df.shape

"""### <font color = #27C3E5> 2.2: </font> <font color = #41EA46> Handle Missing Value </font>"""

df.isnull().sum()

"""#### <font color = blue> Handle Int Col"""

# Missing value of age cols
df = df.interpolate(method='nearest')

"""#### <font color = blue> Handle Obj Col"""

# missing value of Embarked cols
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df.head().isnull().sum()

"""### <font color = #27C3E5> 2.3: </font> <font color = #41EA46> Define Predictor and Target Attributes </font>"""

X = df.iloc[:, 1:]
Y = df.iloc[:, 0]

"""#### <font color = blue> Predictor Attributes"""

X.tail()

"""#### <font color = blue> Target Attribute"""

Y.head()

"""### <font color = #27C3E5> 2.4: </font> <font color = #41EA46> One Hot Encoder (Sex, Embarked) </font>"""

X = pd.get_dummies(X,drop_first = True)
X.head()

"""### <font color = #27C3E5> 2.2: </font> <font color = #41EA46> Split the Data into Training and Testing </font>"""

X_train, X_test, Y_train, Y_test = train_test_split(
                                                    X,
                                                    Y,
                                                    test_size=0.2,
                                                    random_state=0)

"""#### <font color = blue> Training Data"""

print("X_train", X_train.shape)
print("Y_train", Y_train.shape)

"""#### <font color = blue> Testing Data"""

print("X_test", X_test.shape)
print("X_test", Y_test.shape)

"""![Machine Learning Project](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <font color = #950CDF> Part 3: </font> <font color = #4854E8> Build Artificial Neural Network </font>

![ML](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### <font color = #27C3E5> 3.1: </font> <font color = #41EA46> Implementation with Keras</font>

#### <font color = blue> Import Libraries
"""

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from scikeras.wrappers import KerasClassifier

"""#### <font color = blue> Build Model"""

def build_ANN():
    # Initialize our ANN model
    ANN_Keras = Sequential()

    # Add the input layer and first hidden layer with Dropout
    ANN_Keras.add(Dense(5, kernel_initializer = 'uniform', activation = 'relu' , input_dim = 8))
    ANN_Keras.add(Dropout(rate = 0.1))

    # Adding the Second Hidden layer with Dropout
    ANN_Keras.add(Dense(5, kernel_initializer= 'uniform', activation = 'relu'))
    ANN_Keras.add(Dropout(rate = 0.1))

    # Adding the output layer
    ANN_Keras.add(Dense(1, kernel_initializer= 'uniform', activation = 'sigmoid'))

    # Compiling the ANN
    ANN_Keras.compile(optimizer= 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return ANN_Keras

ANN_Keras = KerasClassifier(model= build_ANN, batch_size = 10, epochs = 100)
Accuracies_Train_Data = cross_val_score(estimator = ANN_Keras, X = X_train, y = Y_train, cv = 10, n_jobs= -1)
Accuracies_Train_Data

"""#### <font color = blue> Predict the Test Data"""

Y_pred_keras = cross_val_predict(ANN_Keras, X_test, Y_test, cv = 10)

Y_pred_keras

"""#### <font color = blue> Accuracy Score"""

Accuracy_Keras = cross_val_score(ANN_Keras, X = X_test, y = Y_test, cv = 10)

Accuracy_Keras = Accuracy_Keras.mean()
print('Accuracy Score:', Accuracy_Keras)

"""### <font color = #27C3E5> 3.2: </font> <font color = #41EA46> Implementation with Scikit-Learn</font>

#### <font color = blue> Import Libraries
"""

from sklearn.neural_network import MLPClassifier

"""#### <font color = blue> Init the Model"""

ANN_Sklearn =  MLPClassifier(random_state=1, max_iter=300)

"""#### <font color = blue> Fit the Training Data to Model"""

ANN_Sklearn.fit(X_train, Y_train)

"""#### <font color = blue> Predict the Test Data"""

Y_pred_Sklearn = ANN_Sklearn.predict(X_test)
Y_pred_Sklearn

"""#### <font color = blue> Accuracy Score"""

Accuracy_Sklearn = accuracy_score(Y_pred_Sklearn, Y_test)
print('Accuracy Score:', Accuracy_Sklearn)

"""### <font color = #27C3E5> 3.3: </font> <font color = #41EA46> Comparison (Keras vs. Scikit-Learn) </font>"""

accuracy = [Accuracy_Sklearn, Accuracy_Keras]
label = ["Sklearn", "Keras"]
plt.bar(label, accuracy, color = ['blue', 'red'])
plt.title("Sklearn vs Keras")
plt.xlabel("Artificial Neural Networks")
plt.ylabel("Accuracy")
plt.show()

"""Sklearn gave much better result than Keras. Therefore we use Sklearn Result in Part 4 for Evaluation and Prediction

![Machine Learning Project](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <font color = #950CDF> Part 4: </font> <font color = #4854E8> Evaluate the Result </font>

![ML](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### <font color = #27C3E5> 4.1: </font> <font color = #41EA46> Confusion Matrix</font>
"""

confusion_matrix = confusion_matrix(Y_pred_Sklearn, Y_test)

#[row, column]
TP = confusion_matrix[1, 1]
TN = confusion_matrix[0, 0]
FP = confusion_matrix[0, 1]
FN = confusion_matrix[1, 0]

group_names = ['TN','FP','FN','TP']

group_counts = ["{0:0.0f}".format(value) for value in confusion_matrix.flatten()]

group_percentages = ["{0:.2%}".format(value) for value in confusion_matrix.flatten()/np.sum(confusion_matrix)]

labels = [f"{v1}\n{v2}\n{v3}" for v1, v2, v3 in zip(group_names,group_counts,group_percentages)]

labels = np.asarray(labels).reshape(2,2)

sns.heatmap(confusion_matrix, annot=labels, fmt='', cmap='Greens')

"""### <font color = #27C3E5> 4.2: </font> <font color = #41EA46>  Evaluate the Results </font>

#### <font color = blue>4.2.1: Calculate the Results
"""

# Accuracy Score
Accuracy = accuracy_score(Y_pred_Sklearn, Y_test)
print('Accuracy Score:', Accuracy)

# Precision Score
Precision = precision_score(Y_pred_Sklearn, Y_test)
print('Precision Score:', Precision)

# True positive Rate (TPR) or Sensitivity or Recall
TPR = recall_score(Y_pred_Sklearn, Y_test)
print('True positive Rate:', TPR)

# False positive Rate (FPR)
FPR = FP / float(TN + FP)
print('False positive Rate', FPR)

# F1 Score or F-Measure or F-Score
F1 = f1_score(Y_pred_Sklearn, Y_test)
print('F1 Score:', F1)

# Specificity
Specificity = TN / (TN + FP)
print('Specificity:', Specificity )

# Mean Absolute Error
Error = mean_absolute_error(Y_pred_Sklearn, Y_test)
print('Mean Absolute Error:', Error)

# ROC Area
Roc = roc_auc_score(Y_pred_Sklearn, Y_test)
print('ROC Area:', Roc)

"""#### <font color = blue>4.2.2: Visualize the Results"""

plt.figure(figsize = (12, 5))

result = [Accuracy, Precision, TPR, FPR, F1, Specificity, Error, Roc]
label = ["Accuracy", "Precision", "TPR", "FPR", "F-Score", "Specificity", "Error", "Roc Area"]
colors=[ 'red', 'green', 'blue', 'darkgoldenrod', 'orange', 'purple', 'brown', 'darkcyan']

plt.bar(label, result, color = colors, edgecolor='black')

"""![Machine Learning Project](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## <font color = #950CDF> Part 5: </font> <font color = #4854E8> Making A Single Prediction </font>

![ML](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
"""

col = ["Pclass", "Age", "SibSp", "Parch", "Fare", "Sex", "Embarked", "Survived"]
pd.DataFrame([[3, 36.0, 1, 2, 24.2345, 'Female', 'C', '?']], columns = col)

new_prediction = ANN_Sklearn.predict(np.array([[3, 36.0, 1, 2, 24.2345, 1, 1, 1]]))

if new_prediction == 1:
    print("Survived")
else:
    print("Not Survived")

"""![Machine Learning Project](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

<b>©</b>Amir Ali
"""