# -*- coding: utf-8 -*-
"""SIAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cu0HnqL95hhuFQSvlN6w6nYfsiOt4LtD
"""

import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.applications import VGG16, ResNet50, DenseNet121
from tensorflow.keras.applications.vgg16 import preprocess_input as vgg_preprocess
from tensorflow.keras.applications.resnet50 import preprocess_input as resnet_preprocess
from tensorflow.keras.applications.densenet import preprocess_input as densenet_preprocess
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Lambda, Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.metrics import Precision, Recall
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf

# Load dataset pairs from CSV
pairs_df = pd.read_csv('/content/image_pairs_with_positive_negative.csv')

# Split dataset into training and validation
train_df, val_df = train_test_split(pairs_df, test_size=0.2, random_state=42)

# Function to preprocess images
def preprocess_image(image_path, preprocess_func):
    img = load_img(image_path, target_size=(224, 224))
    img_array = img_to_array(img)
    img_array = preprocess_func(np.expand_dims(img_array, axis=0))
    return img_array

# Function to create a Siamese network
def create_siamese_network(backbone, preprocess_func):
    input_shape = (224, 224, 3)
    input_1 = Input(shape=input_shape)
    input_2 = Input(shape=input_shape)

    # Backbone model
    base_model = backbone(weights='imagenet', include_top=False, pooling='avg')

    # Feature extraction
    feature_1 = base_model(Lambda(preprocess_func)(input_1))
    feature_2 = base_model(Lambda(preprocess_func)(input_2))

    # L1 distance between the two feature vectors
    l1_distance = Lambda(lambda tensors: tf.abs(tensors[0] - tensors[1]))([feature_1, feature_2])

    # Output layer
    output = Dense(1, activation='sigmoid')(l1_distance)

    # Define the model
    model = Model(inputs=[input_1, input_2], outputs=output)

    return model

# Function to compile and train the model
def train_model(model, train_data, val_data, learning_rate, weight_decay):
    # Compile model
    optimizer = Adam(learning_rate=learning_rate, weight_decay=weight_decay)
    model.compile(optimizer=optimizer,
                  loss=BinaryCrossentropy(),
                  metrics=['accuracy', Precision(), Recall()])

    # Training
    (train_images_1, train_images_2), train_labels = train_data
    (val_images_1, val_images_2), val_labels = val_data

    history = model.fit(
        x=[train_images_1, train_images_2],  # Pass the image pairs separately
        y=train_labels,                      # Labels for the pairs
        validation_data=([val_images_1, val_images_2], val_labels),
        epochs=20,
        batch_size=32,                       # Adjust batch size as needed
        callbacks=[EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)]
    )
    return history


# Load data
def load_data(df, preprocess_func):
    images_1 = np.vstack([preprocess_image(row['Image1'], preprocess_func) for _, row in df.iterrows()])
    images_2 = np.vstack([preprocess_image(row['Image2'], preprocess_func) for _, row in df.iterrows()])
    labels = df['Label'].values  # Ensure this column exists
    return (images_1, images_2), labels


# Prepare training and validation data
train_images, train_labels = load_data(train_df, vgg_preprocess)
val_images, val_labels = load_data(val_df, vgg_preprocess)

# Create Siamese networks with different backbones
backbones = [(VGG16, vgg_preprocess), (ResNet50, resnet_preprocess), (DenseNet121, densenet_preprocess)]

for backbone, preprocess_func in backbones:
    model = create_siamese_network(backbone, preprocess_func)
    train_data = ((train_images[0], train_images[1]), train_labels)
    val_data = ((val_images[0], val_images[1]), val_labels)

    # Train with different hyperparameters
    for learning_rate in [1e-3, 1e-4]:
        for weight_decay in [1e-4, 1e-5]:
            print(f"Training with backbone: {backbone.__name__}, LR: {learning_rate}, WD: {weight_decay}")
            history = train_model(model, train_data, val_data, learning_rate, weight_decay)

            # Log results
            print(f"Training complete for LR: {learning_rate}, WD: {weight_decay}")